// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htmglmnjwsyutqaxkahf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0bWdsbW5qd3N5dXRxYXhrYWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTM5ODUsImV4cCI6MjA3MjY2OTk4NX0.Roj1k1YgWSslDrUA4oZQG8N2OsBhZJ2fmmxGB3S6rVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});